### ISSUE TITLE
Coloring of multiline arguments function

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#558]
_From @iddan on January 13, 2018 1:13_

- VSCode Version: 1.19.2
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Write a simple function - see coloring
2. Write a function with multiline arguments - see coloring

Does this issue occur when all extensions are disabled?: Yes

Because of the line break `interview` is not highlighted in blue

<img width="285" alt="screen shot 2018-01-08 at 22 07 08" src="https://user-images.githubusercontent.com/12671072/34690064-588e6614-f4c0-11e7-8005-34b02131a243.png">

Because of the parentheses `async` is highlighted in blue instead of `interview`

<img width="624" alt="screen shot 2018-01-08 at 22 04 12" src="https://user-images.githubusercontent.com/12671072/34689951-fe0f3e84-f4bf-11e7-810b-4eb54944a953.png">

This issue occurs on various of color themes I tested.
  

_Copied from original issue: Microsoft/vscode#41562_

**Comment by mjbvz** [comment]
Please share source text along with the screenshots

**Comment by mjbvz** [comment]
_From @iddan on January 13, 2018 23:54_

```javascript
export const interview = (
   fabricatedCase : FabricatedCase
) : Promise<InterviewTest> => {
```

```javascript
export const interview = async (
   fabricatedCase : FabricatedCase
) : Promise<InterviewTest> => {
   const res = await fetch(API_URL + '/interviews', {
       method: 'POST',
       headers: new Headers({
           'Content-Type': 'application/json',
       }),
       body: JSON.stringify(fabricatedTest),
   });
   const interviewTest = await res.json();
   return interviewTest;
};
```

**Comment by mjbvz** [comment]
Duplicate of #481

**Comment by sheetalkamat** [comment]
Released [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.33 that contains #552 which should address issues reported here. After letting it bake in that extension for 2-3 weeks, I could merge #552

**Comment by iddan** [comment]
<img width="478" alt="screen shot 2018-03-07 at 01 24 07" src="https://user-images.githubusercontent.com/12671072/37064596-45f45c80-21a6-11e8-8898-01e3d7552760.png">
Fixed:
 - Colouring of function name (`interview`)
 - Colouring of type in generic brackets (`InterviewTest`)
Still broken:
 - `async` is highlighted as if it was a function name even though it's a keyword

**Comment by sheetalkamat** [comment]
Fixed and release [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.34 that contains the fix. Please give it a try.

**Comment by iddan** [comment]
Perfect!

**Comment by iddan** [comment]
Here is another use cases still broken though: 
```javascript
export const run = ({
  environment,
  fabricatedCase
}: {
  environment: string,
  fabricatedCase: FabricatedCase
}): Promise<InterviewTest> =>
  fetch(["environments", environment, "run"].join("/"), {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json"
    },
    body: JSON.stringify(fabricatedCase)
  });
```
<img width="547" alt="screen shot 2018-03-08 at 00 13 12" src="https://user-images.githubusercontent.com/12671072/37121367-87edca58-2265-11e8-9b88-95aa11c170bc.png">
